// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCutV0SMtCbg2CemyrbV7HOjiQ-v9OdHAQ',
    appId: '1:233962587677:web:43273e0d5c464a843c28f4',
    messagingSenderId: '233962587677',
    projectId: 'vyra-efe2e',
    authDomain: 'vyra-efe2e.firebaseapp.com',
    storageBucket: 'vyra-efe2e.firebasestorage.app',
    measurementId: 'G-D3KX49HGX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDG-DiXbTYxlnamDT_Cbo9XnvcMHk_49o',
    appId: '1:233962587677:android:378948cbf60a46063c28f4',
    messagingSenderId: '233962587677',
    projectId: 'vyra-efe2e',
    storageBucket: 'vyra-efe2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA81fx-VpIMBFbKwcUwQXBqyaYlW7mKxCI',
    appId: '1:233962587677:ios:c324304e1f61eaac3c28f4',
    messagingSenderId: '233962587677',
    projectId: 'vyra-efe2e',
    storageBucket: 'vyra-efe2e.firebasestorage.app',
    iosBundleId: 'com.example.vyra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA81fx-VpIMBFbKwcUwQXBqyaYlW7mKxCI',
    appId: '1:233962587677:ios:c324304e1f61eaac3c28f4',
    messagingSenderId: '233962587677',
    projectId: 'vyra-efe2e',
    storageBucket: 'vyra-efe2e.firebasestorage.app',
    iosBundleId: 'com.example.vyra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCutV0SMtCbg2CemyrbV7HOjiQ-v9OdHAQ',
    appId: '1:233962587677:web:dd25183476472d443c28f4',
    messagingSenderId: '233962587677',
    projectId: 'vyra-efe2e',
    authDomain: 'vyra-efe2e.firebaseapp.com',
    storageBucket: 'vyra-efe2e.firebasestorage.app',
    measurementId: 'G-QJDX6LJ0X6',
  );
}
