# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Build and distribute production APK"
  lane :prod do
    sh("cd ../.. && flutter pub get")
    sh("flutter build apk --flavor prod -t lib/main_prod.dart")

    # Get the latest commit message
    changelog = sh("git log -1 --pretty=%B").strip

    firebase_app_distribution(
      app: "1:233962587677:android:378948cbf60a46063c28f4",
      apk_path: "../build/app/outputs/flutter-apk/app-prod-release.apk",
      testers: "chiragdhunna2468@gmail.com",
      release_notes: changelog # Pass commit message as release notes
    )
  end

  
end
