name: Internal APK Build

on:
  push:
    branches: [main, develop]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.0"
      - run: flutter pub get
      - run: flutter build apk --flavor staging -t lib/main_staging.dart
      - uses: actions/upload-artifact@v4
        with:
          name: vyra-staging-apk
          path: build/app/outputs/apk/staging/release/app-staging-release.apk
