name: Internal APK Build (Fastlane)

on:
  push:
    branches: [main, develop]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby + Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"

      - name: Install Fastlane Plugins
        run: |
          gem install bundler
          bundle install || bundle init && echo 'gem "fastlane"' >> Gemfile && bundle install
          bundle exec fastlane add_plugin firebase_app_distribution

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.0"
          channel: "stable" # Explicitly specify channel

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Run Fastlane prod lane
        run: |
          cd android
          bundle exec fastlane android prod

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vyra-prod-apk
          path: build/app/outputs/flutter-apk/app-prod-release.apk
