name: Internal APK Build (Fastlane)

on:
  push:
    branches: [main, develop]

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true # Enable caching for gems

      - name: Configure Bundler
        run: |
          bundle config path vendor/bundle
          bundle config deployment true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Setup Fastlane
        run: |
          # Create fastlane directory if missing
          mkdir -p ./android/fastlane
          # Initialize only if not already initialized
          if [ ! -f ./android/fastlane/Fastfile ]; then
            cd android
            bundle exec fastlane init
            cd ..
          fi

      - name: Install Fastlane Plugins
        run: |
          cd android
          bundle exec fastlane add_plugin firebase_app_distribution
          cd ..

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.0"
          channel: "stable"
          cache: true # Enable caching for Flutter dependencies

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Setup Firebase Token
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          echo "FIREBASE_TOKEN=$FIREBASE_TOKEN" >> $GITHUB_ENV

      - name: Run Fastlane prod lane
        run: |
          cd android
          bundle exec fastlane android prod

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vyra-prod-apk
          path: build/app/outputs/flutter-apk/app-prod-release.apk
