name: Internal APK Build (Fastlane)

on:
  push:
    branches: [main, develop]

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Cache Ruby dependencies to speed up the process
      - name: Cache Ruby gems
        uses: actions/cache@v3 # Updated to v3
        with:
          path: android/vendor/bundle
          key: ${{ runner.os }}-ruby-${{ hashFiles('android/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-ruby-

      # Setup Ruby environment
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true # Enable caching for gems

      # Install dependencies (bundler, gems)
      - name: Install dependencies
        run: |
          gem install bundler
          cd android
          bundle install

      # Ensure Fastlane directory and initialize Fastlane if necessary
      - name: Setup Fastlane
        run: |
          cd android/fastlane
          if [ ! -f ./Fastfile ]; then
            bundle exec fastlane init
          fi

      # Install Fastlane plugins (only if not installed)
      - name: Install Fastlane Plugins
        run: |
          cd android/fastlane
          bundle exec fastlane add_plugin firebase_app_distribution

      # Setup Flutter environment (Flutter 3.29.2 to match your local setup)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.2" # Match your local version (Flutter 3.29.2)
          channel: "stable"
          cache: true # Enable caching for Flutter dependencies

      - name: Create .env from GitHub Secrets
        run: |
          echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_ANDROID_API_KEY }}" >> .env
          echo "FIREBASE_APP_ID=${{ secrets.FIREBASE_ANDROID_APP_ID }}" >> .env
          echo "FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_ANDROID_MESSAGING_SENDER_ID }}" >> .env
          echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_ANDROID_PROJECT_ID }}" >> .env
          echo "FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_ANDROID_STORAGE_BUCKET }}" >> .env

      # Install Flutter dependencies
      - name: Install Flutter Dependencies
        run: flutter pub get

      # Setup Firebase Token environment variable
      - name: Setup Firebase Token
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          echo "FIREBASE_TOKEN=$FIREBASE_TOKEN" >> $GITHUB_ENV

      # Run Fastlane 'prod' lane
      - name: Run Fastlane prod lane
        run: |
          cd android/fastlane
          bundle exec fastlane android prod

      # Upload the APK artifact
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vyra-prod-apk
          path: android/app/build/outputs/flutter-apk/app-prod-release.apk
