name: Production APK Build

on:
  push:
    tags:
      - "v*"

jobs:
  build-prod-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.0"
      - run: flutter pub get
      - run: flutter build apk --flavor prod -t lib/main_prod.dart
      - uses: actions/upload-artifact@v4
        with:
          name: vyra-prod-apk
          path: build/app/outputs/apk/prod/release/app-prod-release.apk
